### ISSUE TITLE
As a User, I'd like to see if an inference/a seed has been verified

### ISSUE THREAD

**Issue by sylvanie85** [ai-cfia/nachet-frontend#184]
# Context
Since https://github.com/ai-cfia/nachet-frontend/issues/182, when a user gives feedback, the inference is now updated on the front end view, but it would be nice to see exactly if a feedback has already been gave for a seed or not.

For example here is a picture of Ambrosia artemisiifolia but two of the seeds are classified as Ambrosia psilostachya so I want to give a wrong seed feedback for the one selected.
![image](https://github.com/user-attachments/assets/04c6770b-e663-4dd6-91ea-76848ee77fbb)

I submit the feedback
![image](https://github.com/user-attachments/assets/2350e3c7-c2f0-4795-9761-3f851efe6e29)

And as we can see, it has been applied because the seed is now an Ambrosia artemisiifolia (type 1)
![image](https://github.com/user-attachments/assets/401f4b82-4a6a-49e7-bb80-0c1ae8711799)

But without that, we have no idea which seeds have been verified or not.

# Solution
One solution might be to turn the boxes green when a seed has been verified by the user.

# TODO
Frontend

- [ ] Knowing whether or not a seed has been verified in the inference data
- [ ] Turn the box green if the inference is verified

Backend/Datastore

- [x] https://github.com/ai-cfia/ailab-datastore/issues/109
